sudo: false
language: node_js
before_install:
  - npm install -g npm@6.7.0
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '11'
script:
  - npm start validate
after_success:
  - npx codecov
branches:
  only:
    - master
